#!/usr/bin/env php
<?php
/**
 * Универсальное приложение по созданию навыков и ботов.
 * Скрипт позволяет создавать/удалять БД, а также создавать шаблон для приложения.
 * @version 1.0
 * @author Maxim-M maximco36895@yandex.ru
 */
if (version_compare('7.1.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of PHPUnit is supported on PHP 7.1 and PHP 7.2.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('U_BOT_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('U_BOT_COMPOSER_INSTALL')) {
    require_once __DIR__ . '/../bot/init.php';
    require_once __DIR__ . '/controllers/ConsoleController.php';
    require_once __DIR__ . '/controllers/CreateController.php';
    require_once __DIR__ . '/controllers/InitController.php';
} else {
    require U_BOT_COMPOSER_INSTALL;
}

$param = null;
if ($argv[1] ?? null) {
    $param['command'] = strtolower($argv[1]);
    if (isset($argv[2])) {
        if (strpos($argv[2], '.json') !== -1) {
            if (is_file($argv[2])) {
                $jsonParam = json_decode(file_get_contents($argv[2]));
                if ($jsonParam['config']) {
                    MM\bot\core\mmApp::setConfig($jsonParam['config']);
                }
                $param['appName'] = $jsonParam['name'];
                $param['params'] = $jsonParam;
            }
        } else {
            $param['appName'] = $argv[2];
        }
    }
}
\MM\console\controllers\ConsoleController::main($param);


/**
 * Консольный скрипт
 * =================
 * Назначение
 * ----------
 * Скрипт предназначен для быстрого создания приложения.
 * Он способен создать шаблон приложения.
 * Использование
 * -------------
 * Чтобы воспользоваться скриптом, запустите файл cApp.js, и передайте необходумые параметры.
 * ```bash
 * php ./vendor/bin/ubot ...
 * ```
 *
 * Комманды
 * --------
 * На данный момент поддерживаются 1 команда:
 * - init-db - Создание бд
 * - drop-db - Удаление бд
 * - create - Создать приект
 *
 * При создании проекта, в качестве 2 параметра нужно передать либо название проекта на английском языке, либо json файл с конфигурацией.
 * При передаче json файла, можно создать шаблон приложения определенного типа. Сейчас поддерживается `quiz` - викторина, и пустой проект.
 *
 * Пример json файла
 * -----------------
 * ```json
 * {
 *   "name": "Название проекта (*)",
 *   "type": "Тип проекта. default, quiz",
 *   "config": ["Конфигурация для подключения к бд. Структуру смотри в mmApp.config"],
 *   "params": ["Параметры приложения. Структуру смотри в mmApp.params"],
 *   "path": "Директория, в которой будет создан проект. По умолчанию, проект создается в папке и именем проекта, в дирректории запуска спкипта."
 * }
 * ```
 * '*' - обозначены обязательные поля.
 *
 * Пример использования
 * --------------------
 * Создание пустого проекта:
 * ```bash
 * php ./vendor/bin/ubot create project
 * ```
 * Создание проекта, используя в качестве параметра json
 * ```json
 * {
 *   "name": "project",
 *   "type": "quiz"
 * }
 * ```
 * ```bash
 * php ./vendor/bin/ubot create project.json
 * ```
 */
